### PR TITLE
[istio] fix: handle wildcard hosts in VirtualServices

### LINKED ISSUE #154: istio: invalid convert result
**What happened**:

try to convert following configuration to istio, but rejected by apiserver

**What you expected to happen**:

apiserver didn't reject the converted result.

**How to reproduce it (as minimally and precisely as possible)**:

apply following result to cluster:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - "*"
  gateways:
    - httpbin-gateway
  http:
    - match:
        - uri:
            prefix: /get
        - uri:
            regex: ^/status/[0-9]{3}$
      route:
        - destination:
            host: httpbin
            port:
              number: 8080
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: httpbin
            port:
              number: 8080
```

then running:
```console
ingress2gateway print --providers istio | k apply -f -
I0419 16:42:17.535135   38688 converter.go:148] ignoring field: istio.Gateway[httpbin-gateway].Server[0].Port.Name
gateway.gateway.networking.k8s.io/httpbin-gateway configured
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"kind\":\"HTTPRoute\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"httpbin-idx-0\",\"namespace\":\"default\"},\"spec\":{\"hostnames\":[\"*\"],\"parentRefs\":[{\"group\":\"gateway.networking.k8s.io\",\"kind\":\"Gateway\",\"name\":\"httpbin-gateway\"}],\"rules\":[{\"backendRefs\":[{\"name\":\"httpbin\",\"namespace\":\"default\",\"port\":8080,\"weight\":0}],\"matches\":[{\"path\":{\"type\":\"PathPrefix\",\"value\":\"/get\"}},{\"path\":{\"type\":\"RegularExpression\",\"value\":\"^/status/[0-9]{3}$\"}}]}]},\"status\":{\"parents\":null}}\n"}},"spec":{"hostnames":["*"],"rules":[{"backendRefs":[{"name":"httpbin","namespace":"default","port":8080,"weight":0}],"matches":[{"path":{"type":"PathPrefix","value":"/get"}},{"path":{"type":"RegularExpression","value":"^/status/[0-9]{3}$"}}]}]}}
to:
Resource: "gateway.networking.k8s.io/v1, Resource=httproutes", GroupVersionKind: "gateway.networking.k8s.io/v1, Kind=HTTPRoute"
Name: "httpbin-idx-0", Namespace: "default"
for: "STDIN": error when patching "STDIN": HTTPRoute.gateway.networking.k8s.io "httpbin-idx-0" is invalid: spec.hostnames[0]: Invalid value: "*": spec.hostnames[0] in body should match '^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"kind\":\"HTTPRoute\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"httpbin-idx-1\",\"namespace\":\"default\"},\"spec\":{\"hostnames\":[\"*\"],\"parentRefs\":[{\"group\":\"gateway.networking.k8s.io\",\"kind\":\"Gateway\",\"name\":\"httpbin-gateway\"}],\"rules\":[{\"backendRefs\":[{\"name\":\"httpbin\",\"namespace\":\"default\",\"port\":8080,\"weight\":0}],\"matches\":[{\"path\":{\"type\":\"PathPrefix\",\"value\":\"/\"}}]}]},\"status\":{\"parents\":null}}\n"}},"spec":{"hostnames":["*"],"rules":[{"backendRefs":[{"name":"httpbin","namespace":"default","port":8080,"weight":0}],"matches":[{"path":{"type":"PathPrefix","value":"/"}}]}]}}
to:
Resource: "gateway.networking.k8s.io/v1, Resource=httproutes", GroupVersionKind: "gateway.networking.k8s.io/v1, Kind=HTTPRoute"
Name: "httpbin-idx-1", Namespace: "default"
for: "STDIN": error when patching "STDIN": HTTPRoute.gateway.networking.k8s.io "httpbin-idx-1" is invalid: spec.hostnames[0]: Invalid value: "*": spec.hostnames[0] in body should match '^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by zirain**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #154

**Does this PR introduce a user-facing change?**:

```release-note
[istio] allow & handle wildcard hosts in VirtualServices
```

### CODE REVIEW

**Review by levikobi — COMMENTED** [review]
Thanks @zirain!

/ok-to-test
/cc @LiorLieberman @dpasiukevich

File: .gitignore [hunk 1]
```diff
@@ -26,3 +26,6 @@ go.work
 
 # GolangCI-Lint cache
 /cache
+
+# goland
+.idea
```
Comment (dpasiukevich) [inline .gitignore:31]: I'd suggest to remove these IDE specific files from gitignore. More at https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

File: pkg/i2gw/providers/istio/converter.go [hunk 2]
```diff
@@ -583,6 +583,10 @@ func (c *converter) convertVsHTTPRoutes(virtualService metav1.ObjectMeta, istioH
 		// set istio hostnames as is, without extra filters. If it's not a fqdn, it would be rejected by K8S API implementation
 		hostnames := make([]gatewayv1.Hostname, 0, len(allowedHostnames))
 		for _, host := range allowedHostnames {
+			// '*' is valid in istio, but not in HTTPRoute
+			if host == "*" {
```
Comment (dpasiukevich) [inline pkg/i2gw/providers/istio/converter.go:587]: I left out validation to have less conversion logic and to defer this to the validation in the gw api implementation.

But having validation here is also quite fine. Could we make it a proper one then (from the gw api [HTTPRoute spec](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPRoute))
```
Valid values for Hostnames are determined by RFC 1123 definition of a hostname with 2 notable exceptions:

IPs are not allowed.
A hostname may be prefixed with a wildcard label (*.). The wildcard label must appear by itself as the first label.
```

1. to have a separate fun for the validation of the hostname
2. log if the hostname is discarded during the conversion

File: .gitignore (hunk 1 above)
Comment (zirain) [reply .gitignore:31]: TIL, thanks!

File: pkg/i2gw/providers/istio/converter.go [hunk 3]
```diff
@@ -600,7 +611,7 @@ func (c *converter) convertVsHTTPRoutes(virtualService metav1.ObjectMeta, istioH
 				OwnerReferences: virtualService.OwnerReferences,
 				Finalizers:      virtualService.Finalizers,
 			},
-			hostnames:   hostnames,
+			hostnames:   allowedHostnames,
```
Comment (dpasiukevich) [inline pkg/i2gw/providers/istio/converter.go:614]:
```suggestion
			hostnames:   c.convertHostnames(istioHTTPHosts),
```

File: pkg/i2gw/providers/istio/converter_test.go [hunk 4]
```diff
@@ -1245,6 +1245,96 @@ func Test_converter_convertVsHTTPRoutes(t *testing.T) {
...
+			name: "hosts with '*'",
+			args: args{
+				virtualService: metav1.ObjectMeta{
+					Name:      "test",
+					Namespace: "ns",
+				},
+				istioHTTPRoutes: []*istiov1beta1.HTTPRoute{
+					{
+						Headers: &istiov1beta1.Headers{
+							Request: &istiov1beta1.Headers_HeaderOperations{
```
Comment (dpasiukevich) [inline pkg/i2gw/providers/istio/converter_test.go:1258]: These fields are irrelevant for the test. Could you minimise the istio.HTTPRoute definition for the test case? (e.g. to keep only only header operation: request+add).

File: pkg/i2gw/providers/istio/converter.go [hunk 5]
```diff
@@ -289,10 +289,27 @@ func (c *converter) convertGateway(gw *istioclientv1beta1.Gateway, fieldPath *fi
 	}, nil
 }
 
-func (c *converter) convertVsHTTPRoutes(virtualService metav1.ObjectMeta, istioHTTPRoutes []*istiov1beta1.HTTPRoute, allowedHostnames []string, fieldPath *field.Path) ([]*gatewayv1.HTTPRoute, field.ErrorList) {
+// convertHostnames set istio hostnames as is, without extra filters.
+// If it's not a fqdn, it would be rejected by K8S API implementation
+func (c *converter) convertHostnames(hosts []string) []gatewayv1.Hostname {
+	var resHostnames []gatewayv1.Hostname
+	for _, host := range hosts {
+		// '*' is valid in istio, but not in HTTPRoute
```
Comment (dpasiukevich) [inline pkg/i2gw/providers/istio/converter.go:297]: Could you add the validation to match the gateway api requirements (not only for "*" but rather like in https://github.com/kubernetes-sigs/ingress2gateway/pull/155#discussion_r1573690864)?  

Doing the check for "*" is fine but the proper validation would've been ideal to have if possible.

File: pkg/i2gw/providers/istio/converter.go (hunk 3 above)
Comment (zirain) [reply pkg/i2gw/providers/istio/converter.go:614]: is it good to call that function in a loop?

File: pkg/i2gw/providers/istio/converter.go (hunk 5 above)
Comment (zirain) [reply pkg/i2gw/providers/istio/converter.go:301]: updated

**Comment by dpasiukevich** [comment]
/lgtm
/approve

Thanks for the PR!

**Comment by dpasiukevich** [comment]
@LiorLieberman could you review & approve the PR? Thanks!

File: pkg/i2gw/providers/istio/converter.go [hunk 6]
```diff
@@ -289,10 +291,36 @@ func (c *converter) convertGateway(gw *istioclientv1beta1.Gateway, fieldPath *fi
...
+var hostnameRegexp = regexp.MustCompile(`^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`)
+
+// convertHostnames set istio hostnames as is, without extra filters.
+// If it's not a fqdn, it would be rejected by K8S API implementation
+func convertHostnames(hosts []string) []gatewayv1.Hostname {
+	var resHostnames []gatewayv1.Hostname
+	for _, host := range hosts {
+		// '*' is valid in istio, but not in HTTPRoute
+		if !hostnameRegexp.MatchString(host) {
+			klog.Infof("ignoring host %s, which is not allowed in Gateway API HTTPRoute", host)
```
Comment (LiorLieberman) [inline pkg/i2gw/providers/istio/converter.go:303]: I'd give it severity warning
Same for line 309

File: pkg/i2gw/providers/istio/converter_test.go [hunk 7]
```diff
@@ -1945,3 +1997,41 @@ func Test_converter_generateReferences(t *testing.T) {
...
+			hostnames: []string{"*"},
+			expected:  []gatewayv1alpha2.Hostname{},
+		},
+		{
+			name:      "IP is not allowed",
+			hostnames: []string{"192.0.2.1", "2001:db8::68", "::ffff:192.0.2.1"},
+			expected:  []gatewayv1alpha2.Hostname{},
+		},
+		{
+			name:      "The wildcard label must appear by itself as the first label",
```
Comment (LiorLieberman) [inline pkg/i2gw/providers/istio/converter_test.go:2023]: Does first label means first character?

File: pkg/i2gw/providers/istio/converter_test.go [hunk 8]
```diff
@@ -1945,3 +1997,41 @@ func Test_converter_generateReferences(t *testing.T) {
 		})
 	}
 }
+
+func Test_convertHostnames(t *testing.T) {
```
Comment (LiorLieberman) [inline pkg/i2gw/providers/istio/converter_test.go:2001]: Can we add a testcase for mix of valid and invalid hostnames? 

Like <ip>,*,<some valid hostname>

File: pkg/i2gw/providers/istio/converter.go (hunk 6 above)
Comment (zirain) [reply pkg/i2gw/providers/istio/converter.go]: updated

**Review by LiorLieberman — COMMENTED** [review]
Thanks @zirain ! 
/approve
/lgtm
